# Generated by Django 4.0.4 on 2023-12-11 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=254)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=200, null=True, unique=True)),
                ('register_time', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('level', models.SmallIntegerField(blank=True, default=1)),
                ('shipping_address', models.CharField(max_length=500)),
                ('is_verify', models.BooleanField(default=False)),
            ],
        ),
    ]
