version: '3'

services:
  web:
    image: levindu11/mysite_rtpt:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    command: >
      sh -c "
      while ! timeout 1 bash -c 'cat < /dev/null > /dev/tcp/db/3306'; do
        echo 'Waiting for the MySQL Server';
        sleep 3;
      done;
      echo 'MySQL Server is up - executing command';
      python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
      "
    env_file:
      - .env
    volumes:
      - .:/code
      - static_data:/app/staticfiles
      - media_data:/app/media

    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mysite_rtpt
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_HOST: db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d/
    command:
      --default-authentication-plugin=caching_sha2_password

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
      - ./certs:/etc/nginx/certs
      - static_data:/app/staticfiles
    depends_on:
      - web

volumes:
  mysql_data:
  static_data:
  media_data:
