# Generated by Django 4.1 on 2023-09-06 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='expression_host',
            new_name='ExpressionHost',
        ),
        migrations.RenameModel(
            old_name='purification_method',
            new_name='PurificationMethod',
        ),
    ]
