# Generated by Django 4.0.4 on 2023-09-20 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_rename_expression_host_expressionhost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Vector_name')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('Map', models.ImageField(blank=True, null=True, upload_to='vector_map', verbose_name='Map')),
                ('action', models.CharField(max_length=20, verbose_name='Action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
