# Generated by Django 4.0.4 on 2023-09-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_vector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vector',
        ),
    ]
