# Generated by Django 4.0.4 on 2023-09-20 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_delete_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_name', models.CharField(max_length=20, verbose_name='Vector_name')),
                ('cloning_site', models.CharField(max_length=20, verbose_name='Cloning_site')),
                ('vector_map', models.CharField(max_length=20, verbose_name='Vector_Map')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
                ('C_Gene', models.CharField(max_length=20, verbose_name='C_Gene')),
                ('V_Gene', models.CharField(max_length=20, verbose_name='V_Gene')),
                ('NC5', models.CharField(max_length=20, verbose_name='5NC')),
                ('NC3', models.CharField(max_length=20, verbose_name='3NC')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
