# Generated by Django 4.0.4 on 2023-09-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vector',
            name='status',
        ),
        migrations.AddField(
            model_name='vector',
            name='is_ready_to_use',
            field=models.BooleanField(default=False),
        ),
    ]
