# Generated by Django 4.0.4 on 2023-10-25 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_vector_status_vector_is_ready_to_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vector',
            name='C_Gene',
        ),
        migrations.RemoveField(
            model_name='vector',
            name='V_Gene',
        ),
    ]
