# Generated by Django 4.0.4 on 2023-10-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_vector_c_gene_remove_vector_v_gene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vector',
            name='vector_map',
            field=models.TextField(verbose_name='Vector_Seq'),
        ),
    ]
