# Generated by Django 4.0.4 on 2023-11-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_genesynenzymecutsite_remove_vector_cloning_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vector',
            name='NC3',
            field=models.TextField(max_length=20, verbose_name='3NC'),
        ),
        migrations.AlterField(
            model_name='vector',
            name='NC5',
            field=models.TextField(max_length=20, verbose_name='5NC'),
        ),
    ]
