# Generated by Django 4.0.4 on 2023-11-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_vector_nc3_alter_vector_nc5'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='contained_forbidden_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vector',
            name='forbidden_check_list',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vector',
            name='NC3',
            field=models.TextField(verbose_name='3NC'),
        ),
        migrations.AlterField(
            model_name='vector',
            name='NC5',
            field=models.TextField(verbose_name='5NC'),
        ),
    ]
