# Generated by Django 4.0.4 on 2023-11-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_vector_contained_forbidden_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='gc_content',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
