# Generated by Django 4.0.4 on 2023-11-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='id20',
            field=models.TextField(blank=True, null=True, verbose_name='id20'),
        ),
        migrations.AddField(
            model_name='vector',
            name='iu20',
            field=models.TextField(blank=True, null=True, verbose_name='iu20'),
        ),
    ]
