# Generated by Django 4.0.4 on 2023-11-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_vector_id20_vector_iu20'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vector',
            name='contained_forbidden_list',
        ),
        migrations.RemoveField(
            model_name='vector',
            name='forbid_seq',
        ),
        migrations.RemoveField(
            model_name='vector',
            name='forbidden_check_list',
        ),
        migrations.RemoveField(
            model_name='vector',
            name='gc_content',
        ),
        migrations.AddField(
            model_name='vector',
            name='vector_file',
            field=models.FileField(blank=True, null=True, upload_to='vector_file'),
        ),
        migrations.AlterField(
            model_name='vector',
            name='status',
            field=models.CharField(default='Received', max_length=255),
        ),
    ]
