# Generated by Django 4.0.4 on 2023-11-22 09:03

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_vector_contained_forbidden_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vector',
            name='vector_file',
            field=models.FileField(blank=True, null=True, upload_to=product.models.user_directory_path),
        ),
    ]
