# Generated by Django 4.0.4 on 2023-11-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_vector_vector_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='vector_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Vector_ID'),
        ),
        migrations.AlterField(
            model_name='vector',
            name='NC3',
            field=models.TextField(verbose_name='v3NC'),
        ),
        migrations.AlterField(
            model_name='vector',
            name='NC5',
            field=models.TextField(verbose_name='v5NC'),
        ),
    ]
