# Generated by Django 4.1 on 2023-09-06 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20, verbose_name='Project_name')),
                ('adding_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('antibody_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number')),
                ('total_price', models.PositiveSmallIntegerField(verbose_name='Total_Price')),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.addon')),
                ('express_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.expression_host')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('purification_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.purification_method')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.expressionscale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SHIPPING', 'Shipping'), ('DELIVERED', 'Delivered')], default='CREATED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_center.shoppingcart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
