# Generated by Django 4.1 on 2024-01-15 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_center.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gene_name",
                    models.CharField(max_length=200, verbose_name="Gene name"),
                ),
                (
                    "original_seq",
                    models.TextField(verbose_name="original_seq SeqAA NT"),
                ),
                (
                    "status",
                    models.CharField(default="Need_To_Validate", max_length=255),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                (
                    "forbid_seq",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ForbiddenSeqs",
                    ),
                ),
                ("combined_seq", models.TextField(blank=True, null=True)),
                ("saved_seq", models.TextField(blank=True, null=True)),
                ("gc_content", models.FloatField(blank=True, null=True)),
                (
                    "forbidden_check_list",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contained_forbidden_list",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("i5nc", models.TextField(blank=True, null=True, verbose_name="i5nc")),
                ("i3nc", models.TextField(blank=True, null=True, verbose_name="i3nc")),
                (
                    "species",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.species",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.vector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Project_name",
                    ),
                ),
                ("adding_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Completed"),
                            ("INCOMPLETE", "Incomplete"),
                            ("READYTOSUBMIT", "ReadyToSubmit"),
                        ],
                        default="INCOMPLETE",
                        max_length=15,
                    ),
                ),
                (
                    "antibody_number",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Number"
                    ),
                ),
                (
                    "total_price",
                    models.PositiveSmallIntegerField(verbose_name="Total_Price"),
                ),
                (
                    "sequence_file",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="序列文件"
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.addon",
                    ),
                ),
                (
                    "express_host",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.expressionhost",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
                (
                    "purification_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.purificationmethod",
                    ),
                ),
                (
                    "scale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.expressionscale",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_time", models.DateTimeField(auto_now_add=True)),
                ("inquiry_id", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(default="Pending", max_length=100)),
                ("url", models.URLField(blank=True, verbose_name="report url")),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=user_center.models.OrderInfo.user_directory_path,
                    ),
                ),
                ("gene_infos", models.ManyToManyField(to="user_center.geneinfo")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("genes", models.ManyToManyField(to="user_center.geneinfo")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
