# Generated by Django 4.1 on 2023-09-06 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_expression_host_expressionhost_and_more'),
        ('user_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='express_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.expressionhost'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.expressionscale'),
        ),
    ]
