# Generated by Django 4.1 on 2023-09-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0002_alter_shoppingcart_express_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('INCOMPLETE', 'Incomplete'), ('READYTOSUBMIT', 'ReadyToSubmit')], default='ACTIVE', max_length=15),
        ),
    ]
