# Generated by Django 4.1 on 2023-09-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0003_alter_shoppingcart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='project_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Project_name'),
        ),
    ]
