# Generated by Django 4.1 on 2023-09-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0004_alter_shoppingcart_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('INCOMPLETE', 'Incomplete'), ('READYTOSUBMIT', 'ReadyToSubmit')], default='INCOMPLETE', max_length=15),
        ),
    ]
