# Generated by Django 4.1 on 2023-09-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0005_alter_shoppingcart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='sequence_file',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='序列文件'),
        ),
    ]
