# Generated by Django 4.0.4 on 2023-11-04 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_species'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_center', '0006_shoppingcart_sequence_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True)),
                ('gene_name', models.CharField(max_length=200, verbose_name='Gene name')),
                ('origional_seq', models.TextField(verbose_name='SeqAA NT')),
                ('status', models.CharField(default='Need_To_Validate', max_length=255)),
                ('forbid_seq', models.CharField(blank=True, max_length=255, null=True, verbose_name='ForbiddenSeqs')),
                ('combined_seq', models.TextField(blank=True, null=True)),
                ('saved_seq', models.TextField(blank=True, null=True)),
                ('forbidden_check_list', models.CharField(blank=True, max_length=255, null=True)),
                ('contained_forbidden_list', models.CharField(blank=True, max_length=255, null=True)),
                ('gc_content', models.FloatField(blank=True, null=True)),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.species')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.vector')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('gene_infos', models.ManyToManyField(to='user_center.geneinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gene_infos', models.ManyToManyField(to='user_center.geneinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
