# Generated by Django 4.0.4 on 2023-11-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0007_geneinfo_orderinfo_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneinfo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
