# Generated by Django 4.0.4 on 2023-11-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0008_alter_geneinfo_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='gene_infos',
            new_name='genes',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
