# Generated by Django 4.0.4 on 2023-11-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0009_rename_gene_infos_cart_genes_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geneinfo',
            old_name='origional_seq',
            new_name='original_seq',
        ),
    ]
