# Generated by Django 4.0.4 on 2023-10-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=64, verbose_name='tool name')),
                ('tool_desc', models.TextField(verbose_name='description')),
                ('tool_freq', models.SmallIntegerField(verbose_name='Use frequency')),
                ('tool_icon', models.ImageField(blank=True, upload_to='static/img/tools_icon')),
            ],
        ),
    ]
