# Generated by Django 5.0.6 on 2025-08-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_alias', models.CharField(blank=True, max_length=64, verbose_name='tool alias')),
                ('tool_name', models.CharField(max_length=64, verbose_name='tool name')),
                ('tool_desc', models.TextField(verbose_name='description')),
                ('tool_freq', models.SmallIntegerField(verbose_name='Use frequency')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='tools_icon/', verbose_name='Tool Icon')),
            ],
        ),
    ]
