# Generated by Django 4.0.4 on 2023-10-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='name_alias',
            field=models.CharField(blank=True, max_length=64, verbose_name='tool alias'),
        ),
    ]
